#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Oct 11, 2023 11:10:56 PM -0300  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1000x600+183+56
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Inversiones"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -background $vTcl(actual_gui_bg) -compound center \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text "Control de Inversion" 
    vTcl:DefineAlias "$top.lab48" "LabelTitle" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab49" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Capital Inicial:" 
    vTcl:DefineAlias "$top.lab49" "LabelCI" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab50" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Saldo:" 
    vTcl:DefineAlias "$top.lab50" "LabelSaldo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab51" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Fecha:" 
    vTcl:DefineAlias "$top.lab51" "LabelFechaCI" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab52" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Fecha:" 
    vTcl:DefineAlias "$top.lab52" "LabelFechaSaldo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Egreso" 
    vTcl:DefineAlias "$top.but53" "ButtonEgreso" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Ingreso" 
    vTcl:DefineAlias "$top.but54" "ButtonIngreso" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$top.scr55" \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr55" "treeviewEgreso" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

        $base.scr55.01 configure -columns Col1 -height 4
        $base.scr55.01 configure -columns {Col1}
        $base.scr55.01 heading #0 -text {Tree}
        $base.scr55.01 heading #0 -anchor center
        $base.scr55.01 column #0 -width 233
        $base.scr55.01 column #0 -minwidth 20
        $base.scr55.01 column #0 -stretch 1
        $base.scr55.01 column #0 -anchor w
        $base.scr55.01 heading Col1 -text {Col1}
        $base.scr55.01 heading Col1 -anchor center
        $base.scr55.01 column Col1 -width 233
        $base.scr55.01 column Col1 -minwidth 20
        $base.scr55.01 column Col1 -stretch 1
        $base.scr55.01 column Col1 -anchor w
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$top.scr56" \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr56" "treeviewIngreso" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

        $base.scr56.01 configure -columns Col1 -height 4
        $base.scr56.01 configure -columns {Col1}
        $base.scr56.01 heading #0 -text {Tree}
        $base.scr56.01 heading #0 -anchor center
        $base.scr56.01 column #0 -width 233
        $base.scr56.01 column #0 -minwidth 20
        $base.scr56.01 column #0 -stretch 1
        $base.scr56.01 column #0 -anchor w
        $base.scr56.01 heading Col1 -text {Col1}
        $base.scr56.01 heading Col1 -anchor center
        $base.scr56.01 column Col1 -width 233
        $base.scr56.01 column Col1 -minwidth 20
        $base.scr56.01 column Col1 -stretch 1
        $base.scr56.01 column Col1 -anchor w
    button "$top.but57" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "CargarCI" -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Cargar" 
    vTcl:DefineAlias "$top.but57" "ButtonCI" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$top.tex58" \
        -background white -font "TkTextFont" -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 144 -wrap word 
    $top.tex58 configure -font "TkTextFont"
    $top.tex58 insert end text
    vTcl:DefineAlias "$top.tex58" "TextCI" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$top.tex59" \
        -background white -font "TkTextFont" -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 144 -wrap word 
    $top.tex59 configure -font "TkTextFont"
    $top.tex59 insert end text
    vTcl:DefineAlias "$top.tex59" "TextSaldo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$top.tex60" \
        -background white -font "TkTextFont" -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 194 -wrap word 
    $top.tex60 configure -font "TkTextFont"
    $top.tex60 insert end text
    vTcl:DefineAlias "$top.tex60" "TextFechaCI" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$top.tex61" \
        -background white -font "TkTextFont" -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 194 -wrap word 
    $top.tex61 configure -font "TkTextFont"
    $top.tex61 insert end text
    vTcl:DefineAlias "$top.tex61" "TextFecha" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but62" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Eliminar" 
    vTcl:DefineAlias "$top.but62" "ButtonDeleteEgreso" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but63" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Eliminar" 
    vTcl:DefineAlias "$top.but63" "ButtonDeleteIngreso" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but64" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Exportar" 
    vTcl:DefineAlias "$top.but64" "ButtonExport" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 0 -relx 0.38 -y 0 -rely 0.017 -width 0 -relwidth 0.307 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.162 -width 0 -relwidth 0.087 \
        -height 0 -relheight 0.063 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.288 -width 0 -relwidth 0.057 \
        -height 0 -relheight 0.065 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.36 -y 0 -rely 0.167 -width 0 -relwidth 0.057 \
        -height 0 -relheight 0.063 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.36 -y 0 -rely 0.3 -width 0 -relwidth 0.057 \
        -height 0 -relheight 0.063 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.21 -y 0 -rely 0.4 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.74 -y 0 -rely 0.4 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.scr55 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.467 -width 0 -relwidth 0.485 \
        -height 0 -relheight 0.452 -anchor nw -bordermode ignore 
    place $top.scr56 \
        -in $top -x 0 -relx 0.51 -y 0 -rely 0.467 -width 0 -relwidth 0.485 \
        -height 0 -relheight 0.452 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.13 -y 0 -rely 0.233 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex58 \
        -in $top -x 0 -relx 0.13 -y 0 -rely 0.167 -width 0 -relwidth 0.144 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tex59 \
        -in $top -x 0 -relx 0.13 -y 0 -rely 0.3 -width 0 -relwidth 0.144 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tex60 \
        -in $top -x 0 -relx 0.41 -y 0 -rely 0.167 -width 0 -relwidth 0.194 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.tex61 \
        -in $top -x 0 -relx 0.41 -y 0 -rely 0.3 -width 0 -relwidth 0.194 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.44 -y 0 -rely 0.933 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.94 -y 0 -rely 0.933 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.933 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

