# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capitalinicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 295)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textMonto = QtWidgets.QTextEdit(self.centralwidget)
        self.textMonto.setGeometry(QtCore.QRect(170, 60, 251, 31))
        self.textMonto.setObjectName("textMonto")
        self.textFecha = QtWidgets.QTextEdit(self.centralwidget)
        self.textFecha.setGeometry(QtCore.QRect(170, 100, 251, 31))
        self.textFecha.setObjectName("textFecha")
        self.labelMonto = QtWidgets.QLabel(self.centralwidget)
        self.labelMonto.setGeometry(QtCore.QRect(100, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMonto.setFont(font)
        self.labelMonto.setObjectName("labelMonto")
        self.labelFecha = QtWidgets.QLabel(self.centralwidget)
        self.labelFecha.setGeometry(QtCore.QRect(100, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFecha.setFont(font)
        self.labelFecha.setObjectName("labelFecha")
        self.ButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSave.setGeometry(QtCore.QRect(170, 140, 75, 23))
        self.ButtonSave.setObjectName("ButtonSave")
        self.ButtonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonEdit.setGeometry(QtCore.QRect(260, 140, 75, 23))
        self.ButtonEdit.setObjectName("ButtonEdit")
        self.ButtonDelet = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDelet.setGeometry(QtCore.QRect(350, 140, 75, 23))
        self.ButtonDelet.setObjectName("ButtonDelet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cargar Capital Inicial"))
        self.labelMonto.setText(_translate("MainWindow", "Monto:"))
        self.labelFecha.setText(_translate("MainWindow", "Fecha:"))
        self.ButtonSave.setText(_translate("MainWindow", "Guardar"))
        self.ButtonEdit.setText(_translate("MainWindow", "Editar"))
        self.ButtonDelet.setText(_translate("MainWindow", "Eliminar"))
